### ISSUE TITLE
mismatched counts of registered users

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#1016]
I have three users in my demo repo: the admin, a manager, and a depositor. The depositor serves as a proxy for the manager.

According to the Activity Summary page, there are 5 registered users. I was expecting 4, because about 12 hours ago, audituser was included in this count on this page. 

On the Manager Users page, only the three users are listed.  I was expecting 4, because about 12 hours ago, audituser was included in this count on this page.

Not sure what happened to audituser and who is the fourth or possibly fifth mysterious user being counted. 

I wondered if the proxy depositor was included in count, but adding another proxy relationship did not affect the total user count.

**Comment by jcoyne** [comment]
There's also a system batch user, which may be the other mystery user

**Comment by laritakr** [comment]
The admin manage users page count does not include batch or audit user.
https://github.com/projecthydra-labs/hyrax/blob/master/app/presenters/hyrax/admin/users_presenter.rb#L25-L28

**Comment by hannahfrost** [comment]
This issue appears to have been resolved. The user count in my tenants has been consistently accurate recently.
