### ISSUE TITLE
As a depositor, I want to bulk upload my items where my items have files organized in one or more Bags and have metadata in one or more spreadsheets that meet the metadata target

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#11]

**Comment by jcoyne** [comment]
In the GSE fixture metadata, the bags have metadata within them.  Is this a constraint we can expect locally?  If not, can someone produce a spreadsheet that has the metadata for the GSE bags?

**Comment by mjgiarlo** [comment]
@hannahfrost :arrow_up: :question:

**Comment by hannahfrost** [comment]
@jcoyne I had asked around SUL about available tools to transform the MODS exported from SDR to a spreadsheet for the fixture objects, and came up with nothing. So the answer is - this is a constraint that we can expect locally.

**Comment by jcoyne** [comment]
I can create a test spreadsheet for use with the bags? Should I do that?

**Comment by hannahfrost** [comment]
Sure, sounds great, @jcoyne

**Comment by jcoyne** [comment]
How will the spreadsheet refer to a file that is contained within a bag? Is there a convention for doing that?  Otherwise we could have one column for `bagit_path` and then `file_path` (within the bag).

**Comment by hannahfrost** [comment]
@jcoyne Are you still blocked on this?

**Comment by jcoyne** [comment]
@hannahfrost Yes. I still don't know how we address which files go with each row in the spreadsheet. I made a sample sheet for the metadata here: https://github.com/projecthydra-labs/hybox/blob/master/spec/fixtures/csv/gse_metadata.csv

**Comment by hannahfrost** [comment]
@jcoyne If I add druids to the spreadsheet, can you make the file associations?

**Comment by jcoyne** [comment]
I can easily make them in the Stanford case, because I already have the druids and I know the conventions Stanford uses for structuring/naming the binary content within the bag. However, this doesn't help us fulfill a general purpose requirement where we can take a CSV with metadata and a bunch of bagit bags and associate rows with one particular bag and a particular file in the bag.

**Comment by hannahfrost** [comment]
Oh, yes, I see. (I was conflating our effort to load fixture objects with this ticket.) This reminds me of the METS structmap. We need something like that, don't we?

**Comment by hannahfrost** [comment]
Today's decision: Import spreadsheet (csv), bag path column, multiple file path columns, first file path column is thumb/rep. media

**Comment by hannahfrost** [comment]
Closing because this ticket as currently expressed is no longer useful.
