### ISSUE TITLE
image not showing in viewer

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#1153]
I have an image file in my work. It does not display in the viewer. (All I see is spinning square as it tries to load.)

The file can be downloaded and the thumbnail is visible, but when I click on the thumbnail, an error is thrown.

Here's my work: https://salad.demo.hydrainabox.org/concern/images/687c1d70-3692-4bba-a8b8-5b4806eca907?locale=en#?c=0&m=0&s=0&cv=0

**Comment by jcoyne** [comment]
I think there are two problems here.  The first is that openseadragon is complaining 

<img width="1429" alt="screen shot 2017-05-25 at 2 52 40 pm" src="https://cloud.githubusercontent.com/assets/92044/26467844/e1eacc4c-4159-11e7-8e64-daddbf05305f.png">

The second problem should be fixed by https://github.com/projecthydra-labs/hyku/pull/1151

**Comment by jcoyne** [comment]
I think the IIIF error is because this isn't returning height/width: https://salad.demo.hydrainabox.org/images/9091d3f8-626c-4907-bc5d-c27f31705f68%2Ffiles%2Fbe3e1990-dc18-4676-a8e3-36c5ff7cc11d/info.json

**Comment by hannahfrost** [comment]
@jcoyne I checked the embedded metadata of my local copy of the file and the height/width are there. 

With Ben's help, I got to this: https://salad.demo.hydrainabox.org/images/9091d3f8-626c-4907-bc5d-c27f31705f68%2Ffiles%2Fbe3e1990-dc18-4676-a8e3-36c5ff7cc11d/full/full/0/default.jpg

So somehow the app lost the height/width.

**Comment by jcoyne** [comment]
@hannahfrost that looks like a characterization error. Likely this one: https://app.honeybadger.io/projects/48327/faults/33620461#notice-summary

```
edu.harvard.hul.ois.fits.exceptions.FitsConfigurationException: /tmp/95a139b0-8b99-4570-a83b-284255b4524520170529-24855-cegz4d does not exist or is not readable
```

I wonder if it's possible our characterization jobs are not pulling the file out of S3.  @cbeer any other ideas?

**Comment by jcoyne** [comment]
Uhhhh.... This is telling: https://github.com/samvera-labs/hyrax/blob/46d9afd81670fce9b56ef91b40ac7ef3740193a1/app/jobs/ingest_file_job.rb#L33

**Comment by jcoyne** [comment]
Here's the characterization differences:
<img width="727" alt="screen shot 2017-05-31 at 9 44 15 am" src="https://cloud.githubusercontent.com/assets/92044/26637932/742650a0-45e6-11e7-9c11-00402666d792.png">

<img width="744" alt="screen shot 2017-05-31 at 9 43 53 am" src="https://cloud.githubusercontent.com/assets/92044/26637938/77395184-45e6-11e7-9fa4-9de23b94818d.png">

**Comment by jcoyne** [comment]
When I attempt to use Hanna's original file, mine also doesn't get height & width: 

<img width="751" alt="screen shot 2017-05-31 at 9 51 14 am" src="https://cloud.githubusercontent.com/assets/92044/26638040/c4afe61c-45e6-11e7-950b-5c7ba2d0d048.png">

**Comment by jcoyne** [comment]
When I run this file locally with fits 1.0.5 it works fine.  But on the server there is a problem with fits:
```
$ fits.sh -v
Picked up JAVA_TOOL_OPTIONS: -Xmx128m
1.1.0
[ec2-user@ip-10-0-3-116 ~]$ fits.sh -i dog.jpeg
Picked up JAVA_TOOL_OPTIONS: -Xmx128m
log4j:WARN No appenders could be found for logger (edu.harvard.hul.ois.fits.Fits).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.1.0" timestamp="5/31/17 2:59 PM">
  <identification status="CONFLICT">
    <identity format="JPEG File Interchange Format" mimetype="image/jpeg" toolname="FITS" toolversion="1.1.0">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="file utility" toolversion="5.22" />
      <version toolname="Droid" toolversion="6.1.5">1.01</version>
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">fmt/43</externalIdentifier>
    </identity>
    <identity format="JPEG EXIF" mimetype="image/jpeg" toolname="FITS" toolversion="1.1.0">
      <tool toolname="Exiftool" toolversion="10.00" />
      <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" />
      <version toolname="Exiftool" toolversion="10.00">1.01</version>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.16">1245975</size>
    <creatingApplicationName toolname="Exiftool" toolversion="10.00">Canon PowerShot SD870 IS</creatingApplicationName>
    <lastmodified toolname="Exiftool" toolversion="10.00" status="CONFLICT">2012:04:08 09:50:57</lastmodified>
    <lastmodified toolname="Tika" toolversion="1.10" status="CONFLICT">2012-04-08T09:50:57</lastmodified>
    <created toolname="Exiftool" toolversion="10.00">2012:04:08 09:50:57</created>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/home/ec2-user/dog.jpeg</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">dog.jpeg</filename>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">ce2204e9ca94f1c80f124dfea460c254</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1496242740000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="935">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.1.5" executionTime="203" />
    <tool toolname="Jhove" toolversion="1.16" executionTime="850" />
    <tool toolname="file utility" toolversion="5.22" executionTime="770" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="874" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="802" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="184" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="628" />
    <tool toolname="Tika" toolversion="1.10" executionTime="822" />
  </statistics>
</fits>
```

**Comment by jcoyne** [comment]
Filed https://github.com/harvard-lts/fits/issues/140

**Comment by jcoyne** [comment]
Should we downgrade fits to 1.0.5 on aws?

**Comment by hannahfrost** [comment]
:+1: if that will fix the issue

**Comment by jcoyne** [comment]
<img width="728" alt="screen shot 2017-05-31 at 4 16 08 pm" src="https://cloud.githubusercontent.com/assets/92044/26654480/987f2540-461c-11e7-80f7-65253514ecab.png">

This image now characterizes correctly.
