### ISSUE TITLE
Docker workers won't start

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#1158]
I see this message repeated over and over: 

```
workers_1         | 2017-05-26T17:57:52.273Z 1 TID-gn564p2y0 INFO: Redis is online, 33.442146484 sec downtime
workers_1         | 2017-05-26T17:57:53.241Z 1 TID-gn56r70pg ERROR: Error fetching job: Waited 5 sec
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:86:in `block (2 levels) in pop'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `loop'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:78:in `block in pop'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `synchronize'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool/timed_stack.rb:77:in `pop'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:89:in `checkout'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:61:in `block in with'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `handle_interrupt'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/connection_pool-2.2.1/lib/connection_pool.rb:60:in `with'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq.rb:92:in `redis'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/fetch.rb:36:in `retrieve_work'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:91:in `get_one'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:101:in `fetch'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:84:in `process_one'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/processor.rb:73:in `run'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:17:in `watchdog'
workers_1         | 2017-05-26T17:57:53.242Z 1 TID-gn56r70pg ERROR: /usr/local/bundle/gems/sidekiq-5.0.0/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by mjgiarlo** [comment]
High priority.

**Comment by randalldfloyd** [comment]
@jcoyne Yes those are the errors we've been trying to troubleshoot here at IU. We thought it was something about our Docker setup on our shared server but we see it on our local dev environments as well.

**Comment by mjgiarlo** [comment]
@randalldfloyd You see this outside of the Docker context? Huh, OK. I wonder if we need some code in `config/environments/development.rb` that uses the value provided here: https://github.com/samvera-labs/hyku/blob/master/config/settings.yml#L43 That might be unrelated?

**Comment by mjgiarlo** [comment]
@randalldfloyd Can you see in your Rails server output what job backend seems to be processing or trying to process background jobs?

**Comment by mjgiarlo** [comment]
For testing: https://github.com/samvera-labs/hyku/pull/1160

**Comment by mjgiarlo** [comment]
OK. :point_up: is unrelated. The docker installation runs in the `production` env, and `environments/production.rb` already has the line that says "pull the queue adapter from Settings." And our docker build has an env variable that should effectively set the Settings queue adapter to Sidekiq.

**Comment by randalldfloyd** [comment]
@mjgiarlo I think maybe I wasn't clear, I meant we see this on our server and local machines using Docker to deploy Hyku.  We haven't tried a shared full local install without Docker. But regarding the problem described above, we see this as soon as we do `docker build ; docker up` without even creating accounts/tenants or in any way kicking off jobs.

**Comment by mjgiarlo** [comment]
OK, @randalldfloyd. Even with the change @cbeer made on Wednesday?

**Comment by randalldfloyd** [comment]
@mjgiarlo Right, I just did a `docker down ; docker build` before commenting to make sure.  I'm assuming that's the correct way to make sure everything is fresh.

**Comment by mjgiarlo** [comment]
@randalldfloyd I don't know enough about docker to say, unfortunately. When's the last time you pulled the latest code from Hyku?

**Comment by jcoyne** [comment]
@mjgiarlo this is occurring on the freshest code.

**Comment by randalldfloyd** [comment]
@mjgiarlo My bad, I should have said I did `git pull ; docker build` so it's fresh.

**Comment by mjgiarlo** [comment]
Dang. OK.

**Comment by randalldfloyd** [comment]
@mjgiarlo BTW, it's hard for me to tell what the actual impact of these frequent errors are.  I can create a tenant so the solr/fedora/redis endpoint jobs must be completing via Sidekiq, but I still can't get files attached to works. I can't tell if the latter has anything to do with this bug.

**Comment by dlpierce** [comment]
Looks like running a Redis cluster inside Docker is not a simple affair:

https://redis.io/topics/cluster-tutorial#redis-cluster-and-docker
https://github.com/docker-library/redis/issues/79

Is running with `DISABLE_REDIS_CLUSTER=true` like hyku's non-Docker setup suggests feasible to do?

**Comment by jcoyne** [comment]
@dlpierce DISABLE_REDIS_CLUSTER doesn't affect how redis is deployed in docker.

**Comment by dlpierce** [comment]
Right, we would also replace the three redis services with a single non-cluster service.

On May 26, 2017 4:54 PM, Justin Coyne <notifications@github.com> wrote:

@dlpierce<https://github.com/dlpierce> DISABLE_REDIS_CLUSTER doesn't affect how redis is deployed in docker.

**Comment by jcoyne** [comment]
Cool! That's the best plan I can think of

**Comment by mjgiarlo** [comment]
Have thoughts on the above, @cbeer?

**Comment by mjgiarlo** [comment]
@jcoyne are you planning to pair up with @cbeer this week to troubleshoot? Or should we go with the above workaround?

**Comment by mjgiarlo** [comment]
More on what I'm seeing with a fresh docker-compose installation (some related, some not):

1. Run `docker-compose up -d`
1. Create a tenant
1. View system status page (should all be OK)
1. Upload a new work. Notice that file attachment does not work (because workers don't process jobs, as is already documented here).
1. Have a look at Sidekiq errors: `docker-compose logs workers`
1. Shut down: `docker-compose down`
1. Start back up to surface other errors: `docker-compose up -d`
1. View system status page for your previously created tenant again and notice both Redis and Solr are down
1. View `docker-compose ps` and notice both `redis_sentinel` and `workers` exited with `1`
1. View `docker-compose logs workers` and see the `getaddrinfo: Name or service not known` error
1. View `docker-compose logs redis_sentinel` and see the following error:
```
redis_sentinel_1  | *** FATAL CONFIG FILE ERROR ***
redis_sentinel_1  | Reading the configuration file, at line 10
redis_sentinel_1  | >>> 'sentinel monitor redis_cluster redis_primary 6379 2'
redis_sentinel_1  | Duplicated master name.
```

**Comment by mjgiarlo** [comment]
@jcoyne @cbeer @dlpierce :point_up:

**Comment by jcoyne** [comment]
I don't have any idea.  Possibly due to:

```
    environment:
      - MASTER=redis_primary
      - MASTER_NAME=redis_cluster
```

**Comment by mjgiarlo** [comment]
We haven't been able to make progress on #1173. @randalldfloyd @dlpierce are y'all inclined to take a hack at this?

**Comment by randalldfloyd** [comment]
@mjgiarlo @jcoyne Yeah we can try to team up on that here. I've been busy on local stuff but we're going to start getting ping'd again here about the beta test so we better take a stab at it. @dlpierce had a start on a single redis node config but he was out the first part of the week.
