### ISSUE TITLE
Remove "Background image CC by-nc-sa by f2b1610"

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyku#1167]
### Descriptive summary

I suggest removing "Background image CC by-nc-sa by f2b1610" from the homepage. The link (https://flic.kr/p/eirxaf) is broken, but in reality most, if not all, repositories will change the banner image, rendering this redundant and incorrect.

**Comment by jcoyne** [comment]
I believe the CC by-nc-sa license requires us to cite the creator. This link worked when the image was acquired (thanks Verizion) and I have no other way of citing the creator.

**Comment by geekscruff** [comment]
Could we replace the image with something local that we don't have to cite? Or leave it blank?

**Comment by jcoyne** [comment]
I'm not particularly attached to that image, but I feel like it should have a default image in place.

**Comment by jcoyne** [comment]
Perhaps an alternative ticket is "Make it easer to change hyrax.background_attribution_html" or "Make footer an editable content block"?

**Comment by geekscruff** [comment]
Yes, I agree.I'll create that.

**Comment by mjgiarlo** [comment]
This has been ticketed in samvera/hyrax#189. Closing. Thanks!
