### ISSUE TITLE
Share tab is not showing up for new Works

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyku#1168]
### Descriptive summary

The share tab is not showing up for new Works in Hyku v1.0.0.beta1.

![image](https://cloud.githubusercontent.com/assets/722117/26581583/3e9c5ada-4535-11e7-9f4a-3bde3dc035f1.png)

The share tab *does* show in batch upload, and also for filesets and collections.

### Expected behavior

Share tab should appear.

### Actual behavior

Share tab does not appear.

### Steps to reproduce the behavior

1. With default workflow set on the default admin set
2. Create new work
3. Look for the share tab ... it's not there

**Comment by jcoyne** [comment]
@geekscruff I believe this was fixed by https://github.com/samvera-labs/hyku/pull/1156, but you'd have to create a new admin set in order to see the result. Can you verify this is fixed after updating for new admin sets?

**Comment by mjgiarlo** [comment]
:point_up: @geekscruff ?

**Comment by geekscruff** [comment]
After a git pull I can confirm it's appearing now w/o having to create a new admin set (the default one is set to default workflow out of the box). I'll close this. Thanks!
