### ISSUE TITLE
Download does not set the correct filename (or extension)

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#1172]
When I go to a file_set show view like this and click the download button It just saves as a UUID (on Firefox): https://salad.demo.hydrainabox.org/concern/file_sets/9091d3f8-626c-4907-bc5d-c27f31705f68  

Possibly missing the filename in the  `Content-Disposition:` header.  Use the original file name for this value if possible.

**Comment by darrenleeweber** [comment]
If I get past some current work, I'll look at this one (just not assigning myself until I start working on it, so it's open for anyone to tackle for now).

**Comment by jcoyne** [comment]
This is a problem only in hyku (not hyrax) because `Hydra::PCDM::File#file_name` is returning `['9091d3f8-626c-4907-bc5d-c27f31705f68']`.

**Comment by mjgiarlo** [comment]
This is no longer a problem in Hyku.
