### ISSUE TITLE
batch upload of works results in multiple instances of same work

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#1198]
Using the Batch Work Upload, I added 5 files. Each of the 5 files was processed 3 times to become a work, resulting in 15 works, 3 for each file.

Screen grab below shows some of this duplication in the Works listing.

![screenshot 2017-06-02 10 45 47](https://cloud.githubusercontent.com/assets/1801076/26737862/d13832fe-4780-11e7-98c3-186674251094.png)

**Comment by hannahfrost** [comment]
I was able to reproduce this bug with a different set of files.

**Comment by jcoyne** [comment]
I was unable do duplicate this on AWS.  Can you show me what you're doing?

**Comment by jcoyne** [comment]
I think this may be fixed by #1124. I think the job that creates the work was dying, is not idempotent and was being restarted by the worker.

**Comment by jcoyne** [comment]
@hannahfrost is it possible that this was your first deposit of any kind with a new user?

**Comment by hannahfrost** [comment]
@jcoyne New tenant, new user, two batch uploads sessions.

**Comment by hannahfrost** [comment]
@jcoyne Right no, files, and when I try to edit the work, I get the same "unauthorized" message reported in #1090

Do you still need to me show you what I was doing?

**Comment by jcoyne** [comment]
@hannahfrost If you try another batch, with an existing user, who has uploaded something previously, then do you still get this bug?

**Comment by hannahfrost** [comment]
@jcoyne I'll try another batch next.

Note that the file count for the admin set where all these extra works were created, as displayed on the Repository Activity Summary screen, is off. It says 7 files, but there are 11 unique files uploaded (not to mention the redundant ones that may or may not be attached to the redundant works). 
![screenshot 2017-06-02 15 26 36](https://cloud.githubusercontent.com/assets/1801076/26747102/834b46f8-47a8-11e7-9cd2-695087fe3ea4.png)

**Comment by hannahfrost** [comment]
@jcoyne So in the same tenant, as one of the original users who experienced this issue with a batch upload previously, I batch uploaded 5 new images. (all screenshots, all small png files). 

After saving all 5, I went to the Works page and found that for the work title image 1, no thumbnail generated and there is no file attached. The other 4 image works seemed fine.

Approx 1-2 minutes later, I returned again to the Works page and see that a second set of the 5 works has been created. The second instance of the work titled Image 1 has a thumbnail and a file to download. 

![screenshot 2017-06-02 15 43 03](https://cloud.githubusercontent.com/assets/1801076/26747563/7ec620b4-47ab-11e7-8578-368ee43db7bc.png)

Poking around the 10 works, they are not all ready for display in the UV at the same time. Some are delayed, appearing only as a downloadable file with the message "viewer not available" (or something like that).  Basically it is as if the file is ready before the viewer is.

Now ten minutes later, and I have 4 sets of the works. It just keeps making them!

File count on activity summary page did not change -- with 5 new unique files uploaded -- but total number of works did increase accurately.

**Comment by jcoyne** [comment]
@hannahfrost okay, it looks like this problem correlates closely with https://github.com/samvera-labs/hyku/issues/1208

**Comment by hannahfrost** [comment]
@jcoyne I see both this issue and #1208 are closed, but I just recreated the same problem. Is the fix not yet pushed to the demo site or do we have a problem again?

**Comment by jcoyne** [comment]
@hannahfrost yeah, probably not in demo yet.

**Comment by hannahfrost** [comment]
@jcoyne This bug is occurring again. 
![screenshot 2017-06-08 10 40 30](https://user-images.githubusercontent.com/1801076/26942442-ede18580-4c36-11e7-9b26-8fa7c0140f68.png)

**Comment by hannahfrost** [comment]
@jcoyne But in this case, it was not a batch job, it was a single work with multiple files. The dessert_apple file should only appear once in the work.

**Comment by jcoyne** [comment]
@hannahfrost This appears to be due to a problem with Fedora. 
I see this in the log:
```
ERROR 17:11:08.533 (WildcardExceptionMapper) Exception intercepted by WildcardExceptionMapper: Error parsing media type ‘cannot open `/tmp/40e8273e-1ea8-48ec-916c-e78bc06ba1ea20170608-25523-m6g42x’ (No such file or directory)‘
```

**Comment by mjgiarlo** [comment]
That is a super weird exception. This is worrisome.

**Comment by atz** [comment]
Gotta love getting error messages in your data stream...

**Comment by mjgiarlo** [comment]
@hannahfrost I see these issues are closed, and it's not :100: clear to me what resolved them. For the heck of it, I uploaded a work to the demo instance with 20-odd files and didn't see any problems. Resolved, I suppose. ;)

**Comment by hackmastera** [comment]
@jcoyne was the WildcardExceptionMapper in the fedora log? or in the Rails log? Thanks!

**Comment by jcoyne** [comment]
@hackmastera neither, it was in the elasticbeanstalk log, but it probably originated in Fedora.
