### ISSUE TITLE
No notifications in Docker when file processing is completed

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyku#1201]
When I deposit a work, I never get notifications. Not sure if this means all notifications are borked, though I suspect they are.

**Comment by mjgiarlo** [comment]
Also seeing this in AWS.

**Comment by dlpierce** [comment]
@mjgiarlo Notifications seem to be working in Docker when transferring a work or depositing a work while using the mediated deposit workflow. The default workflow does not have notifications.  Is there a specific notification you are not seeing?

**Comment by mjgiarlo** [comment]
@dlpierce I may be in the wrong about this, after all. The notification that I expected to see was about a file being attached to the work I uploaded. I failed to notice the effect of a change I made last month, though:

https://github.com/samvera-labs/hyrax/pull/918/files#diff-47652dff0fa74e32b525304941f57220L9

This removed that notification. I'm not sure I intended that change, so I totally spaced on this. Fair to close this as a `wontfix`.

**Comment by dlpierce** [comment]
@mjgiarlo Digging deeper, these event notifications are being added to the user's activity/event log, not the user's mailbox. Going to Dashboard -> Your Activity -> Notifications does not show events, and Dashboard -> Your Activity -> Profile does not have the Highlighted/Activities tabs like the profile screens have when going through Manage Users.

**Comment by mjgiarlo** [comment]
@dlpierce OK, thanks for continuing the analysis. Since I mistakenly wrote up this ticket, do you think there is any related work to be done here?

**Comment by dlpierce** [comment]
@mjgiarlo Yes, Dashboard -> Your Activity -> Profile should show your activity. Might be able to use the same view partial as the Manage Users interface? I'm open to other design ideas too.

**Comment by mjgiarlo** [comment]
@dlpierce I'm not sure we want to do that in advance of yet TBD design: https://github.com/samvera-labs/hyku/issues/434 How would you feel about closing this issue and grabbing another from waffle?

Sorry for the goose chase, Daniel.

**Comment by dlpierce** [comment]
Not a problem.
