### ISSUE TITLE
Revise layout of Works show page

### ISSUE THREAD

**Issue by ggeisler** [samvera-labs/hyku#1215]
Design TBD, but based on what's shown in https://github.com/samvera-labs/hyku/issues/1033.

**Comment by ggeisler** [comment]
Mockup below. Suggest this be implemented before #1033.

![hyrax-mockups_graffle__work_-_show_page](https://user-images.githubusercontent.com/101482/26939994-f6fea8cc-4c2d-11e7-99b6-9838592e84ca.png)

**Comment by hannahfrost** [comment]
Looks good to me, @ggeisler

**Comment by jcoyne** [comment]
@ggeisler Items means Files and child Works.

**Comment by mjgiarlo** [comment]
Looks great, @ggeisler!

**Comment by jcoyne** [comment]
@ggeisler Would you mind showing what this mockup should look like when there's a particularly long title? May I suggest:

> A Comparative Study of Artificial Neural Networks Using Reinforcement
               Learning and Multidimensional Bayesian Classification Using Parzen
               Density Estimation for Identification of {GC-EIMS} Spectra of Partially
               Methylated Alditol Acetates on the World Wide Web

**Comment by ggeisler** [comment]
@jcoyne Something like this, where we just wrap the title as much as we need to?

![show-work-long-title](https://user-images.githubusercontent.com/101482/27648424-60422902-5be3-11e7-9896-457ca6964c2a.png)

I think it still looks decent. If we want to structure the HTML as side-by-side columns (work title | action buttons) we might have to experiment to decide if it's 9-3 or 8-4, etc. and we might need to adjust the columns used for different viewport widths, but that should be relatively easy to figure out when the page is restructured.

Since the Feature button is seen by a small subset of users (admins with the privileges to feature works), we might be able to use a wider column for the title by showing the Feature button on its own line, when needed:

![show-work-long-title-alt](https://user-images.githubusercontent.com/101482/27648613-034732aa-5be4-11e7-8a3d-a0f940844c97.png)

I think breaking the Feature button to its own line is acceptable, even if the title is short and the Feature button is the only thing making the title bar take two lines, because relatively few users will see it that way (again, only admins with feature privileges). (And, realistically, most work titles will probably wrap to at least two lines anyway?)

**Comment by jcoyne** [comment]
Thanks @ggeisler that gives me more to go on. 👍

**Comment by hannahfrost** [comment]
Recast this ticket in https://github.com/samvera/hyrax/issues/2050. (Turns out there was not so much to decompose after all. Oh well).
