### ISSUE TITLE
Select menu part of the main search box is inconsistent/too long

### ISSUE THREAD

**Issue by ggeisler** [samvera-labs/hyku#1225]
There seems to be a difference in the way the select menu in the search box acts depending on whether you are a logged-in user or not. 

If you are logged in, you get something like this, where the "All of _institution name_" is shown in the part of the select menu that is visible even when not selected (part with light gray background): 

![admin](https://user-images.githubusercontent.com/101482/26942386-b4297046-4c36-11e7-83c6-9a3e77cd8c46.png)

In contrast, if I'm not logged in I just see "All" in the non-dropdown part of the menu:

![user](https://user-images.githubusercontent.com/101482/26942371-a4f415cc-4c36-11e7-9606-8dec9c6ab146.png)

I suggest that even when logged in the display should be the same as when I'm not logged in, with only "All" showing, as in the second screenshot. Showing the whole institution name could potentially make the search box much wider and thus cause unattractive wrapping issues unless the user has a wide viewport. It's fine to show the whole institution name when the menu is selected, as the second screenshot shows.

As far as I can tell, this is not an issue in Hyrax, only Hyku, but maybe I'm missing something.

**Comment by jcoyne** [comment]
I'm not seeing that behavior. Perhaps it's browser dependent?
![Screen Shot 2017-06-09 at 8.16.00 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/551447cce61b760b00ac12d4/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b77256454fa6b7191a370f1132d4f5f5f5edd3c4a4356bcbbd671f3e57862804e0eeb853b5b20956e13f8bfd11fb853b3208b4bd7e5b58248d2f42f67b6d5db1063474f4dcbed5727a39b41c95cff4ce14c51a6103f64e0762431.png)

**Comment by jcoyne** [comment]
I tested on Safari 10.1, Firefox 53, and Chrome 58 on Mac and none of these browsers exhibit that behavior.

**Comment by ggeisler** [comment]
Okay I think we can assume it's not a real issue. I'm not sure how I got into that state (my first screenshot was from the hosted version and I wasn't doing any web inspector code modifications) but I can't reproduce now so I'll close this.
