### ISSUE TITLE
Incorrectly set location can't be edited while creating new work

### ISSUE THREAD

**Issue by chmayo** [samvera-labs/hyku#1241]
When creating a new work, if you select the wrong location from the list pulled up by GeoNames, you can't change it. The field becomes uneditable after you've selected something.

I was creating a work with a picture that I wanted to tag with "Lookout Mountain" and the Georgia location popped up first. I selected it, and then realized the picture was drawn from a segment of the mountain that's actually in Tennessee. I tried to delete or modify the field and I couldn't. When this happens, you have to abandon the work you're creating and start over.

Not sure to what extent this info helps, but we're running a local non-docker based install (I will add more specifics when I get them from my applications person) and I'm using Firefox.

**Comment by hannahfrost** [comment]
@chmayo Good catch! I will prioritize this fix.

**Comment by jcoyne** [comment]
Yes, there's definitely a problem where "add another" isn't working.

**Comment by chmayo** [comment]
Oh, interesting. I was also not seeing the "remove" feature before because we were not running from the latest commit. I got my colleague in charge of the application to update and restart; now I can remove one I've entered, but it's impossible to add another either before or after doing that.

**Comment by jcoyne** [comment]
Probably due to `TypeError: $(...).size is not a function`
