### ISSUE TITLE
Rake task to create global (non-tenant) user

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1242]
The current method for creating a super-admin user to manage tenants, requires signing up for a global user account first: https://github.com/samvera-labs/hyku/wiki/Create-super-admin-user.

Now that https://github.com/samvera-labs/hyku/issues/1203 is complete, disabling open sign-up on stack build also removes the ability to sign up as a global user. There needs to be another method for creating these global user accounts. The simplest option is likely a rake task, but that may need discussion.

**Comment by mjgiarlo** [comment]
@hannahfrost We should make sure this is in an appropriate spot in teh wafflez.

**Comment by hannahfrost** [comment]
@mjgiarlo @bbranan This sounds important so moved it to the ready column.
