### ISSUE TITLE
Turn off open tenant creation

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1243]
Now that there is an interface which allows for the creation of tenants by super-administrators, it should be possible to disable the open creation of tenants by anyone. This is an absolute must for any production multi-tenant system.

I expect that, similar to https://github.com/samvera-labs/hyku/issues/1203, it would work best to be able to turn this off for an application stack via an environment variable.

**Comment by jcoyne** [comment]
Is this a duplicate of #735?

**Comment by bbranan** [comment]
Yes, this appears to be a duplicate of #735

**Comment by mjgiarlo** [comment]
My bad.
