### ISSUE TITLE
User invite emails not being sent

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1250]
In the super-admin UI there is the option to "Add or invite new administrator (via email)". The form submits properly, and a notice in the log is created that captures the content of the email, but no emails are actually sent.

It appears the work needed is to configure `devise_invitable` to use SES to send out messages. (https://github.com/scambra/devise_invitable)

**Comment by mjgiarlo** [comment]
FWIW, I was able to invite my Gmail account to a tenant in the demo stack.

**Comment by bbranan** [comment]
I was able to invite my gmail account as well, though 2 out of 3 attempts landed in the spam folder. Looking again, the invitations I sent before writing this ticket appear to have eventually landed in my duraspace email, but also in the spam folder. So the invitation emails do appear to be sent, however the "from" address is: please-change-me-at-config-initializers-devise@example.com, which is less than ideal, and likely explains why the mail is being categorized as spam.

**Comment by bbranan** [comment]
Closing in favor of https://github.com/samvera-labs/hyku/issues/1265
