### ISSUE TITLE
Universal Viewer in full screen mode does not use the full screen

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1251]
Issue:

When a user selects the “Full Screen” option in the UV, the viewer renders on only part of the screen (as seen in the attached screenshot). This issue appears on a Mac in both Chrome and Safari. The UV does work as expected in full screen mode in Firefox. Example URL: http://stlawu.pilot.hykudirect.org/concern/images/1f6af6ca-21c6-414a-ae67-6f6a46863011?locale=en

Analysis:

After a little checking around, it appears that the styling for height of 500px is still applied in full screen mode, which then gets centered vertically, and it overflows down from there.

Background Specs:

OS: macOS Sierra Version 10.12.5 
Hardware: Mac Pro 
Browsers:

* Chrome: Version 58.0.3029.110 (64-bit) 
* Safari: Version 10.1.1 (12603.2.4) 
* Firefox: 52.2.0 (64-bit)

This issue was reported by Eric Williams-Bergen
of St. Lawrence University

---

I can verify that this issue also presents in Chrome on Windows 10.

The unnecessary header is created by the CSS element:

.viewer {height: 500px}

acting on the div with class="uv viewer"

**Comment by bbranan** [comment]
![full-screen-uv-chrome](https://user-images.githubusercontent.com/519674/27231438-a0724316-5280-11e7-8b3e-1fcb817762cb.png)

**Comment by tpendragon** [comment]
We had to do this: https://github.com/pulibrary/plum/pull/710/files
