### ISSUE TITLE
initializers/riiif.rb def logger

### ISSUE THREAD

**Issue by jrochkind** [samvera-labs/hyku#1307]
What is this doing?

https://github.com/samvera-labs/hyku/blob/master/config/initializers/riiif.rb#L15-L17

It's trying to define a `logger` method where now?  I think that's probably defining it at top-level ruby object, or else in some random part of Rails stack, probably not what's intended. 

That config file is recommended as a starter at: https://github.com/RepoCamp/ahc/wiki/IIIF#install-a-riiif-config

**Comment by jcoyne** [comment]
Fixed in #1313
