### ISSUE TITLE
Align Hyku catalog search results view with Hyrax

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyku#1344]
The Hyku catalog search results page shows title and creator, whereas Hyrax shows keyword, creator, depositor, date uploaded, and date modified

**Comment by nwoodward** [comment]
Is this as straightforward as syncing some of the Blacklight config in the controller

https://github.com/samvera-labs/hyku/blob/master/app/controllers/catalog_controller.rb

with the config in the initializer template in Hyrax?

https://github.com/samvera/hyrax/blob/master/lib/generators/hyrax/templates/catalog_controller.rb

**Comment by mjgiarlo** [comment]
@nwoodward If I remember correctly, yes, that should do it.
