### ISSUE TITLE
Turning off transfer of ownership should remove the option from menus

### ISSUE THREAD

**Issue by vantuyls** [samvera-labs/hyku#1370]
### Descriptive summary

Currently, turning off transfer of ownership in the Dashboard - Settings - Technical page does not remove transfer of ownership from menus in the repository (e.g. the item Action drop down menus in the My Works page). 

Attempting to use transfer of ownership when it is turned off only results in being redirected to the homepage with the error: "You are not authorized to access this page" (see image)

<img width="1424" alt="screen shot 2017-07-13 at 3 01 23 pm" src="https://user-images.githubusercontent.com/9534576/28190526-2fcbfe7a-67e0-11e7-8fa5-b12cb55d9d06.png">

### Expected behavior

Turning off transfer of ownership makes this option in all elements of the UI go away. 

### Actual behavior

Turning off transfer of ownership leaves the option in UI and using that option results in an unhelpful message.

**Comment by mjgiarlo** [comment]
@vantuyls Should we move this to Hyrax?

**Comment by vantuyls** [comment]
ack. yeah, too many tabs open. want me to copy it over there or do you have some magical github power that can just move it?

**Comment by mjgiarlo** [comment]
Pls copy, good sir.

**Comment by vantuyls** [comment]
done
