### ISSUE TITLE
Support downloads (eg. a PDF of the whole paged item) via Universal Viewer by including renderings in the IIIF Manifest

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyku#1372]
### Descriptive summary

I would like to add support for downloading files via Universal Viewer. This will support the use case of a paged item where there are images of each page to display in the viewer and a PDF download of the whole to be offered as a single download.

This is already supported in Universal Viewer and would display  like so:

![iiif_download](https://user-images.githubusercontent.com/722117/28206519-219a9458-687e-11e7-96db-c4954bb05a95.PNG)

In IIIF there are various linking properties. Providing a display/download URL is achieved with a [rendering linking property](http://iiif.io/api/presentation/2.1/#linking-properties), like so:

```
"rendering": {
    "@id": "http://example.org/iiif/book1.pdf",
    "label": "Download as PDF",
    "format": "application/pdf"
  }
```

### Proposed approach:

In Hyku:

* Add a new property 'rendering' mirroring the code for representative. This property would only be shown for items responding true to `image?`. This property would be used to select one or more FileSets to be used as renderings for the Work. 
* In the ManifestEnabledWorkShowPresenter add a 'rendering' method to build a hash as per the above fragment.

There's a bit more detail in this [gist](https://gist.github.com/geekscruff/4c3c89a674300eee8983381db18b0f26)

In IIIF_Manifest:

* Add code to process the rendering method and add the rendering to the sequence.

I would like feedback on the idea and proposed approach @samvera/hyrax-code-reviewers

**Comment by mjgiarlo** [comment]
I have to defer to @jcoyne, who has done the most work in and around this part of Hyku. (Justin is working on another sprint this week, so hang in there.)

I would love to support this!

**Comment by geekscruff** [comment]
@mjgiarlo Thanks! I'll probably do a bit of prototyping over in my fork. Even if it all changes, it's good Hyku/Hyrax learning stuff.

**Comment by mjgiarlo** [comment]
@geekscruff So @jcoyne is away for a number of weeks at this point, thus I'd encourage you to move forward with this work and pls do feel free to share PRs early and often over here! Happy to chime in and test as you go.
