### ISSUE TITLE
More option in facets is not firing

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/hyku#1438]
### Descriptive summary

When there are more than 5 options in a browse facet, a link to show 'more' is displayed. Nothing happens when clicking on this.

There are some javascript errors:
![image](https://user-images.githubusercontent.com/722117/30820969-84b7f0a4-a21b-11e7-801e-5a21d1f555bb.png)

Confirmed broken in https://iceland.demo.hydrainabox.org 

It *isn't* broken in the Hyrax demo: https://demo.curationexperts.com/ so seems to be Hyku-specific.

### Expected behavior

More options!

### Actual behavior

No more options!

### Steps to reproduce the behavior

1. Add several items with a variety of metadata, making sure that you have more than 5 options for one of the facets (eg. Creator or Resource Type).
2. Select 'more'

### Related work

Link to related tickets or prior related work here.

**Comment by geekscruff** [comment]
This works when testing Hyku with newer Hyrax (beta4), suspect due to newer blacklight version.

**Comment by mjgiarlo** [comment]
@geekscruff Thanks for testing! I will look into updating Hyku to use the newest Hyrax this week.

**Comment by mjgiarlo** [comment]
@geekscruff See #1440.
