### ISSUE TITLE
Remove Config gem monkey-patch

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyku#1464]
We added a [monkey-patch of the Config gem](https://github.com/samvera-labs/hyku/pull/1463) to support reading boolean Config values via ENV variables. Once the [upstream PR to the Config gem](https://github.com/railsconfig/config/pull/180) has been merged and a new version of the gem has been released, we should remove our monkey-patch.

**Comment by mjgiarlo** [comment]
Heads-up, @tdonohue

**Comment by tdonohue** [comment]
Closing as monkey-patch (#1463) was reverted in favor of #1465.  Will create a new "technical debt" ticket though for #1465
