### ISSUE TITLE
Unable to get S3 to work with Compose

### ISSUE THREAD

**Issue by fradeve** [samvera-labs/hyku#1509]
Sorry in advance if this is not the right place to ask, but I will be happy to contribute to the wiki / documentation if this gets fixed so future users will have easier times.

### Descriptive summary

Hyku checkout: 85343d14cb93b19f65b6c13ce7e5ed7a3021cbab

I am running Hyku using the provided `docker-compose.yml`, where I have added the following environment variables in `app`

```
    - SETTINGS__S3__UPLOAD_BUCKET=hyku-pilot
    - AWS_ACCESS_KEY_ID=some_key
    - AWS_SECRET_ACCESS_KEY=some_access_key
    - AWS_REGION=eu-west-1
```
I have edited the CarrierWave configuration as [documented](https://github.com/sorentwo/carrierwave-aws#usage) in the `carrierwave-aws` gem, to have the following in `config/initializers/carrierwave_config.rb`:

```
require 'carrierwave'

if Settings.s3.upload_bucket
    CarrierWave.configure do |config|
      config.storage = :aws
      config.aws_bucket = Settings.s3.upload_bucket
      config.aws_acl = 'bucket-owner-full-control'
      config.asset_host = 'https://s3-eu-west-1.amazonaws.com/hyku-pilot'
      config.aws_authenticated_url_expiration = 60 * 60 * 24 * 365
      config.aws_credentials = {
        access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
        secret_access_key: ENV['AWS_SECRET_ACCESS_KEY'],
        region:            ENV['AWS_REGION']
      }
    end
end
```

### Expected behavior

The Hyku stack should be able to run without problems and the uploaded files should be present in the defined S3 bucket.

### Actual behavior

The `app` service (and any other service extending it in the compose YML) will stop with the following error:

```
initialize_app_1  | CarrierWave::UnknownStorageError: Unknown storage: aws
```

### Related work

Write documentation on how the S3 integration has been achieved and how to configure it (I've read in the specs that `fog` has been replaced by `carrierwave-aws`, but docs are missing details about how to configure both). I'd be happy to help to write this down.

**Comment by fradeve** [comment]
I've also been suggested to look into this: https://github.com/hybox/aws/blob/master/templates/fcrepo.yaml#L141-L150

**Comment by orangewolf** [comment]
@fradeve Is this still open for you? I wonder if you had the aws group bundled in your build? You might check the value of the BUNDLE_WITHOUT env variable inside your docker container.

**Comment by orangewolf** [comment]
Thank you for following up! Nice to get it off the books
