### ISSUE TITLE
I have a suggestion of forming Hyku Whatsapp group... This will help us build a platform of learning

### ISSUE THREAD

**Issue by eddamalique01** [samvera-labs/hyku#1513]
### Descriptive summary

Include what version of Hyku relates to this issue (0.x, 1.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by jcoyne** [comment]
Sounds good to me.  Please reserve github issues for software bugs/features.  See https://wiki.duraspace.org/pages/viewpage.action?pageId=87460391 for the official Samvera communications channels. Maybe bring up this suggestion on the mailing list.
