### ISSUE TITLE
Kindly assist me on this: I am receiving the following error while starting the server, considering that rails, solr and fedora are active.

### ISSUE THREAD

**Issue by eddamalique01** [samvera-labs/hyku#1514]
### Descriptive summary

Include what version of Hyku relates to this issue (0.x, 1.x, HEAD, etc.) if appropriate, and any relevant tracebacks if you're reporting a bug.

### Rationale

Provide the rationale or user story that describes "why" this issue should be addressed. Especially if this is a new feature or significant change to the existing implementation.

### Steps to reproduce the behavior

1. Do this
1. Then do this...

### Related work

Link to related tickets or prior related work here.

**Comment by mjgiarlo** [comment]
Hi! What's the error?
