### ISSUE TITLE
Syntax error in devise gem on latest version of Ruby

### ISSUE THREAD

**Issue by nwoodward** [samvera-labs/hyku#1544]
### Descriptive summary

The version of devise used in Hyku (4.3.0) contains a syntax error when using Ruby 2.5.0. It has been fixed in version 4.4.0.

### Rationale
 
The devise gem used in Hyrax has been updated to 4.5.0, and Hyku will need the same treatment.

### Related work

https://github.com/plataformatec/devise/issues/4736

**Comment by nwoodward** [comment]
I think this would be resolved by #1542

**Comment by geekscruff** [comment]
Fixed by #1554
