### ISSUE TITLE
Mock-ups for batch review and editing of metadata

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#291]
[See list of user stories](https://docs.google.com/document/d/1b5wMz4iRsiH4vKIPMcSl6SQBSCXonf_CfkCn45e6WHA/edit#heading=h.dmelhyz4g1i7)

**Comment by hannahfrost** [comment]
Audrey Altman is going to pick this one up.

**Comment by mjgiarlo** [comment]
Great, @hannahfrost! I'd be happy to add her as assignee (and add her to the Hydra organization) once have her GitHub ID handy.

**Comment by hannahfrost** [comment]
I have pinged her on Slack to request to join the Lerna team

**Comment by hannahfrost** [comment]
I believe this ticket is finished, based on the mockups provided here: https://docs.google.com/document/d/1J3B6Fu24e-wNSP_Xtnqit3ArV9x8sGxQOUB6DyUVhxY/edit#heading=h.uw17uar98q56
