### ISSUE TITLE
Balancing the various requirements of a work's relationship to a "collection"

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#300]
Based on the needs of potential adopters we surveyed, two requirements for Hydra in a Box are:
- an item must not be required to be in a collection (for the case of the one-off submission from a one-off depositor)
- an item should be able to be in more than one collection (for purposes of creating curated exhibits)

Given recent conversations about implementing Admin Sets in Lerna, I take the above to mean:
- a Work that is not designated for a specifically scoped Admin Set is assigned to the repository's default (undifferentiated) Admin Set
- a Work will always be assigned to (be a member of) a single "home" Admin Set, and that we need another mechanism to be able to include a Work in an assemblage of curated/exhibited Works from any Admin Set

Are we on track to being able to support these requirements?

**Comment by mjgiarlo** [comment]
So much depends on what we read into the term "collection," but I think we're OK given your interpretation (and given that Lerna/Sufia/CC currently do not support exhibits).

**Comment by hannahfrost** [comment]
@jcoyne @mjgiarlo Your thoughts? :arrow_up:
