### ISSUE TITLE
Mockup: Collections

### ISSUE THREAD

**Issue by ggeisler** [samvera-labs/hyku#446]
TBD based on resolution of whether we need collections, given admin sets and user folders/favorites.

**Comment by ggeisler** [comment]
I think the intent of this ticket is covered by the many specific collection-related tickets (with mockups) we are filing in Hyrax: https://github.com/samvera/hyrax/issues?utf8=%E2%9C%93&q=is%3Aopen%20is%3Aissue%20project%3Asamvera%2Fhyrax%2F1%20%22Collections%3A%22

Suggest we close this one and rely on the Hyrax collection tickets. If, when the Hyrax collection-related development is completed over the next couple of months, we find there is additional Hyku-specific collection work that needs to be done, we could make new tickets then.

**Comment by hannahfrost** [comment]
I agree. Thanks for all your work on this @ggeisler
