### ISSUE TITLE
As a Sufia adopter, when I set up Sufia, I want to choose a default metadata schema that is based on either Dublin Core or DPLA MAPv4

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#6]

**Comment by anarchivist** [comment]
Can we clarify what the difference is here, and what we mean by "Dublin Core"? The reason I ask is that DPLA MAP's descriptive properties on `dpla:SourceResource` are mostly a mixture of DC 1.1 and DCTerms.

**Comment by mjgiarlo** [comment]
@anarchivist I suspect what @hannahfrost and I meant by "Dublin Core" here is "the largely DC-based metadata that is provided by default in CC and Sufia." It's a mix of DC11 and DCTERMS, with other properties thrown in from FOAF, EDM, RDFS, and so on: https://github.com/projecthydra/curation_concerns/blob/master/app/models/concerns/curation_concerns/basic_metadata.rb#L6-L69

Thanks!

**Comment by anarchivist** [comment]
👍

**Comment by hannahfrost** [comment]
I think this ticket has been superseded by #292 and thus is worth closing.
