### ISSUE TITLE
Get Started page is confusing

### ISSUE THREAD

**Issue by hannahfrost** [samvera-labs/hyku#614]
When I click "Get Started" on demo.hydrainabox.org, I should be taken the sign-in / create account page. And then I should be taken to the create a repository page.

**Comment by mjgiarlo** [comment]
Accounts are currently scoped to tenants, so at the moment you can't create an account before creating a repository. (Yes, this means anyone can create a repository.) So you *could* create an account before, but when switching into your new tenant, it would no longer be visible AFAIK.

**Comment by atz** [comment]
The whole architecture of tenancy needs to have a governing design document interpretable to developers.
