### ISSUE TITLE
Tenant creation should be restricted to superadmins

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyku#735]
Disable self-provisioning of tenants.

Blocked by #734

**Comment by mjgiarlo** [comment]
Decomposed from #728.

**Comment by atz** [comment]
To reframe w/ #728's scoping questions: is this a decision for Hyku overall, our AWS demo, or both?

**Comment by mjgiarlo** [comment]
@atz Perhaps we can put this behind a config in Hyku so we can turn it on in our AWS instance without committing all eventual Hyku users to it?

**Comment by atz** [comment]
Blocker is now https://github.com/projecthydra-labs/hyku/issues/725

**Comment by mjgiarlo** [comment]
Note that this issue is assigned to @tdonohue but is not yet being worked on.

**Comment by jcoyne** [comment]
Unblocked by https://github.com/samvera-labs/hyku/pull/1218

**Comment by bbranan** [comment]
I expect that, similar to #1203, it would work well to turn off open tenant creation for an application stack via an environment variable. This allows the AWS deployment to have it turned off by default, but local installs to still have this option.

**Comment by tdonohue** [comment]
At this point, I'm unlikely to get to this ticket prior to OR2017. So, if this has escalated in priority, someone is welcome to steal this ticket (and/or unassign me).
