### ISSUE TITLE
Disable multitenancy on the Docker deploy

### ISSUE THREAD

**Issue by jcoyne** [samvera-labs/hyku#898]
Otherwise it raises a routing error here: https://github.com/projecthydra-labs/hyku/blob/master/app/controllers/application_controller.rb#L27

We need to have this value return false.
```
Settings.multitenancy.enabled
```

We can do this by setting the environment variable `SETTINGS__MULTITENANCY__ENABLED=false`

**Comment by jcoyne** [comment]
When I set this, I get passed the error, but it's still presenting me with the  account sign up controller.  @cbeer do you have any insights into what might be going on?

**Comment by mjgiarlo** [comment]
This no longer appears to be the case. Closing.
